# docker-compose.yml
# Configuração dos serviços para ambiente Docker:
# - db: Postgres configurado com usuário, senha e banco.
# - etl: Container da aplicação ETL, depende do banco e usa variáveis de ambiente para conexão.
# Volumes e portas configurados para persistência e acesso.

services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: beanalytic
      POSTGRES_DB: beanalytic
    volumes:
      # Script de inicialização para criação de schemas/tabelas
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  etl:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: beanalytic
      DB_USER: postgres
      DB_PASS: beanalytic
    volumes:
      # Monta a pasta atual no container para acesso ao código
      - ./:/root/Desktop/beanalytic
    command: ["python", "main.py"]

volumes:
  pgdata:
